### PR TITLE
Implement go.mod and add option to only print differences

### PR DESCRIPTION
**Pull request by jerbob92**
Hi there, 

Thanks for this work!
I made some changes to this repository, thought it might be useful to some!

### CODE REVIEW

**Comment by nsf** [comment]
Hello. I'm not sure about go.mod file you added. You see, it pulls in deps for webdemo, which is not really part of the lib. I understand that I should probably reorganize the repo a bit. The lib itself has no dependencies.

Let's look at the code.

I don't like "DontPrintMatches" name for this variable. Perhaps a different wording for it would do. Let's say "SkipMatches". Also "match" doesn't sound descriptive. Maybe it's worth commenting what it means. Something like "When true, matching JSON elements will be skipped, reducing the output noise".
https://github.com/nsf/jsondiff/pull/14/files#diff-ab5d2ac49314d80a4296040d50fa94c987b46467f4b69661ee9459f8e103f754R57

As for implementation. If it works, I can accept it. But I'll have a look at the algo closer this weekend.

Overall I'm positive about adding this change, because there are cases when it bothers me as well (long output). Just wasn't a big priority for me. I still use this lib for some proprietary projects I work on.

**Comment by jerbob92** [comment]
Yeah I noticed the dependencies too. 
Feel free to make any changes to the code if you feel like names can be better :)
The code I added isn't that great too, but I couldn't really add this without doing it like this or completely restructuring a lot of the code.

**Comment by smyrman** [comment]
If there are any subfolders that pull in these deps (e.g. examples folder), you can add a go.mod file to the relevant sub-folder(s) to ignore it.

**Comment by jerbob92** [comment]
> If there are any subfolders that pull in these deps (e.g. examples folder), you can add a go.mod file to the relevant sub-folder(s) to ignore it.

This didn't really work for me.

@nsf I have renamed the `DontPrintMatches` option and added a comment. I have fixed the go.mod file by renaming webdemo to _webdemo for now. Go mod ignores folders/files that start with `_`.

**Comment by nsf** [comment]
Thanks for the fixes. I'll merge it sometime this weekend. Will make a proper version tag for it too.

**Comment by jerbob92** [comment]
Thanks :) Please note that I added `go 1.16` to the go.mod, but the minimum version might be a way lower version?

**Comment by nsf** [comment]
Hello again. I added this option, but I rewrote it from scratch. One of the concerns I have here is how to print mismatching arrays. Because just printing mismatching values gives little clue as where to find the elements. So I added a bunch of options to format skipped values.

It looks like this:
image

Sadly there is no way to turn it off.

I'm open for discussion about this feature.

As such I will defer releasing a version tag for now. We need to test this thing a bit. Also I'm thinking about adding a sort of "official" CLI diff tool (aka cmd).

**Comment by jerbob92** [comment]
@nsf Thanks, looks good!
Looking at the code, it doesn't look like much work to not print anything when the following items are/return empty:
```
Skipped
SkippedSliceString
SkippedKeysString
```

And then it will basically the same behavior as in this PR.

**Comment by nsf** [comment]
Eh, it's not that simple. There will be issues with dangling commas. But I think I can solve it. It will just require more effort to do so. Not sure I want to. But we'll see.

**Comment by jerbob92** [comment]
Why would that cause dangling commas? I don't really see any reason why they would appear?

Honestly, it feels a bit odd that you suddenly decide to build this yourself after a year and then add extra functionality that's not requested and we can't disable?

**Comment by nsf** [comment]
This is what I'm refering to as "danling commas":
image

As for your "odd feeling". Nobody forces you to use it. I thought I explained my view on this project earlier in this thread (https://github.com/nsf/jsondiff/pull/14#issuecomment-920976016):
>Overall I'm positive about adding this change, because there are cases when it bothers me as well (long output). Just wasn't a big priority for me. I still use this lib for some proprietary projects I work on.

**Comment by jerbob92** [comment]
Ah yes, I see. Those commas look off in the other output as well, shouldn't they be gone there as well?

And ofcourse I know I don't have to use it. I can just use my fork. Just ruins the "giving back" experience, thst's all.

**Comment by nsf** [comment]
There is no definitive answer about commas. Because the format I'm printing things out in is not really a JSON format. However, my goal was to try resembling JSON. There is even option to print out actual JSON (never used it myself).

"giving back" is more about creating your own projects other people find useful. Contributing to other people's projects inevitably leads to clashes with their own opinions about it. But your pull request was useful, because once it's there for me it becomes a choice: "merge it or do something better". Of course "better" as I see it fit for my project. Others may disagree.

I'll try to do something about commas and making this whole "skipping" text optional sometime this week.

**Pull request closed without merging**
